// <auto-generated>
//     This code was generated by the .NET ToolStrip Customizer.
//     http://toolstripcustomizer.codeplex.com/
// </auto-generated>

using System.Drawing;
using System.Windows.Forms;

namespace Lextm.SharpSnmpLib
{
    class VS2012DarkColorTable : ProfessionalColorTable
    {
        public override Color ButtonSelectedHighlight
        {
            get { return ButtonSelectedGradientMiddle; }
        }
        public override Color ButtonSelectedHighlightBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonPressedHighlight
        {
            get { return ButtonPressedGradientMiddle; }
        }
        public override Color ButtonPressedHighlightBorder
        {
            get { return ButtonPressedBorder; }
        }
        public override Color ButtonCheckedHighlight
        {
            get { return ButtonCheckedGradientMiddle; }
        }
        public override Color ButtonCheckedHighlightBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonPressedBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonSelectedBorder
        {
            get { return Color.FromArgb(255, 63, 63, 63); }
        }
        public override Color ButtonCheckedGradientBegin
        {
            get { return Color.FromArgb(255, 109, 109, 109); }
        }
        public override Color ButtonCheckedGradientMiddle
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color ButtonCheckedGradientEnd
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color ButtonSelectedGradientBegin
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color ButtonSelectedGradientMiddle
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color ButtonSelectedGradientEnd
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color ButtonPressedGradientBegin
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color ButtonPressedGradientMiddle
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color ButtonPressedGradientEnd
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color CheckBackground
        {
            get { return Color.FromArgb(255, 138, 138, 138); }
        }
        public override Color CheckSelectedBackground
        {
            get { return Color.FromArgb(255, 138, 138, 138); }
        }
        public override Color CheckPressedBackground
        {
            get { return Color.FromArgb(255, 105, 105, 105); }
        }
        public override Color GripDark
        {
            get { return Color.FromArgb(255, 195, 195, 195); }
        }
        public override Color GripLight
        {
            get { return Color.FromArgb(255, 87, 87, 87); }
        }
        public override Color ImageMarginGradientBegin
        {
            get { return Color.FromArgb(255, 50, 50, 50); }
        }
        public override Color ImageMarginGradientMiddle
        {
            get { return Color.FromArgb(255, 33, 33, 33); }
        }
        public override Color ImageMarginGradientEnd
        {
            get { return Color.FromArgb(255, 33, 33, 33); }
        }
        public override Color ImageMarginRevealedGradientBegin
        {
            get { return Color.FromArgb(255, 33, 33, 33); }
        }
        public override Color ImageMarginRevealedGradientMiddle
        {
            get { return Color.FromArgb(255, 33, 33, 33); }
        }
        public override Color ImageMarginRevealedGradientEnd
        {
            get { return Color.FromArgb(255, 33, 33, 33); }
        }
        public override Color MenuStripGradientBegin
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color MenuStripGradientEnd
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color MenuItemSelected
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color MenuItemBorder
        {
            get { return Color.FromArgb(255, 90, 90, 90); }
        }
        public override Color MenuBorder
        {
            get { return Color.FromArgb(255, 90, 90, 90); }
        }
        public override Color MenuItemSelectedGradientBegin
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color MenuItemSelectedGradientEnd
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color MenuItemPressedGradientBegin
        {
            get { return Color.FromArgb(255, 90, 90, 90); }
        }
        public override Color MenuItemPressedGradientMiddle
        {
            get { return Color.FromArgb(255, 90, 90, 90); }
        }
        public override Color MenuItemPressedGradientEnd
        {
            get { return Color.FromArgb(255, 90, 90, 90); }
        }
        public override Color RaftingContainerGradientBegin
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color RaftingContainerGradientEnd
        {
            get { return Color.FromArgb(255, 135, 135, 135); }
        }
        public override Color SeparatorDark
        {
            get { return Color.FromArgb(255, 195, 195, 195); }
        }
        public override Color SeparatorLight
        {
            get { return Color.FromArgb(255, 87, 87, 87); }
        }
        public override Color StatusStripGradientBegin
        {
            get { return Color.FromArgb(255, 77, 77, 77); }
        }
        public override Color StatusStripGradientEnd
        {
            get { return Color.FromArgb(255, 77, 77, 77); }
        }
        public override Color ToolStripBorder
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color ToolStripDropDownBackground
        {
            get { return Color.FromArgb(255, 90, 90, 90); }
        }
        public override Color ToolStripGradientBegin
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color ToolStripGradientMiddle
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color ToolStripGradientEnd
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color ToolStripContentPanelGradientBegin
        {
            get { return Color.FromArgb(255, 33, 33, 33); }
        }
        public override Color ToolStripContentPanelGradientEnd
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color ToolStripPanelGradientBegin
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color ToolStripPanelGradientEnd
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color OverflowButtonGradientBegin
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color OverflowButtonGradientMiddle
        {
            get { return Color.FromArgb(255, 68, 68, 68); }
        }
        public override Color OverflowButtonGradientEnd
        {
            get { return Color.FromArgb(255, 44, 44, 44); }
        }
    }
}